name: fancy_counter_app
description: "A new Flutter project."
publish_to: "none"
version: 1.3.0+1

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.1"

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  mesh_gradient: ^1.3.8
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/google_fonts/Teko/
    - assets/images/
  fonts:
    - family: Teko
      fonts:
        - asset: assets/google_fonts/Teko/Teko-Regular.ttf
        - asset: assets/google_fonts/Teko/Teko-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Teko/Teko-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Teko/Teko-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Teko/Teko-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
